name: Build and Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build Leveldb.net/LevelDB.NET.csproj --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack Leveldb.net/LevelDB.NET.csproj --configuration Release --no-build

    - name: Publish to GitHub Packages
      run: dotnet nuget push Leveldb.net/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
